language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t song9605302/docker-frontend-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true song9605302/docker-frontend-test npm run test

after_success:
  - docker build -t song9605302/docker-frontend ./frontend
  - docker build -t song9605302/docker-backend ./backend
  - docker build -t song9605302/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push song9605302/docker-frontend
  - docker push song9605302/docker-backend
  - docker push song9605302/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-fullstack-app
  env: Dockerfullstackapp-env
  bucket_name: elasticbeanstalk-us-east-1-433612818736
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY