language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t song9605302/docker-fullstack-app -f Dockerfile.dev ./frontend

script:
  - docker run -e CI=true song9605302/docker-fullstack-app npm run test

after_success:
  - docker build -t song9605302/docker-frontend ./frontend
  - docker build -t song9605302/docker-backend ./backend
  - docker build -t song9605302/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push song9605302/docker-frontend
  - docker push song9605302/docker-backend
  - docker push song9605302/docker-nginx