version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    volumes:
      - /app/node_modules
      - ./backend:/app

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: myapp

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - "3000:80"